after_failure:
- echo "After failure message!"
after_script:
- echo "ProtoCI build was a:$BINSTAR_BUILD_RESULT" | tee artifact1.txt
after_success:
- echo "ProtoCI BUILD SUCCESS"
engine:
- python
script:
 - conda build .
install_channels:
- defaults
- python
package: protoci
platform:
 - linux-64
 - linux-32
 - win-64
 - win-32
 - osx-64
 - osx-32
user: conda-team

package:
  name: protoci
  version: 0.0.6

build:
  number: 0
  script:
    - conda build .
