package:
  name: protoci
  version: 0.1.0

source:
  git_rev: 0.1.0
  git_url: https://github.com/ContinuumIO/ProtoCI

build:
  number: 1

requirements:
  build:
    - setuptools
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
    - pycosat
    - pytest
  run:
    - networkx
    - requests
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
    - pycosat
    - pytest
about:
  summary: Helps with building conda packages in anaconda-build.

