package:
  name: protoci
  version: 0.0.33

source:
  git_rev: 0.0.33
  git_url: https://github.com/ContinuumIO/ProtoCI

build:
  number: 1
  no_link:
    bin/*.py #[not win]
    bin\*.py #[win]
requirements:
  build:
    - setuptools
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
    - pycosat
  run:
    - networkx
    - requests
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
    - pycosat
about:
  summary: Helps with building conda packages in anaconda-build.

test:
  commands:
    - which protoci-sequential-build #[not win]
    - which protoci-difference-build #[not win]
    - which protoci-split-packages #[not win]
    - which protoci-submit #[not win]
    - where protoci-sequential-build #[win]
    - where protoci-difference-build #[win]
    - where protoci-split-packages #[win]
    - where protoci-submit #[win]
