package:
  name: protoci
  version: 0.0.6

source:
  git_rev: 0.0.6
  git_url: https://github.com/ContinuumIO/ProtoCI

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
  run:
    - python
    - networkx
    - requests
    - networkx
    - pyyaml
    - requests
    - jinja2
    - psutil
about:
  summary: Helps with building conda packages in anaconda-build.

test:
  imports:
    - protoci
    - networkx
    - yaml
    - jinja2
  commands:
    - ls protoci-sequential-build #[not win]
    - ls protoci-difference-build #[not win]
    - ls protoci-split-packages #[not win]
    - ls protoci-submit #[not win]
    - dir protoci-sequential-build #[win]
    - dir protoci-difference-build #[win]
    - dir protoci-split-packages #[win]
    - dir protoci-submit #[win]
